site_name: Skupper docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - navigation.sections

docs_dir: docs
site_dir: output

nav:
  - Kubernetes: kubernetes/skupper.md
  - Podman: podman/skupper.md
  - Diffs: diffs/kubernetes-podman.md

plugins:
  - search

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences